#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = '17e039b'
__repo_version__ = '17e039b'
__fingerprint__ = '17e039b85f5155d1c34605b0f107000d12db9744'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
